---
title: |
  | H-ARC
  | Abstraction and Reasoning Corpus
  | Adapted for Human Behavior
author: Michael Pascale
date: now
date-format: 'MMMM D, YYYY H:mm z'
knitr:
  opts_chunk:
    dev: svglite
    dev.args:
      svglite: {bg: "transparent"}
execute:
  cache: false
keep-yaml: false
keep-md: true
format:
  revealjs:
    theme: [serif, custom.scss]
    slide-number: true
    editor: visual
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(dplyr)
library(purrr)
library(stringr)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(cowplot)
library(forcats)

# Original colors were changed.
# arcpal <- list('#000000', '#0074D9', '#FF4136', '#2ECC40', '#FFDC00',
#            '#AAAAAA', '#F012BE', '#FF851B', '#7FDBFF', '#870C25')
arcpal <- list('#2B2B2B', '#248ADA', '#C71010', '#1FC719', '#F7DE28', 
               '#878494', '#F954F2', '#EE6000', '#6B23A9', '#8B5A28')

names(arcpal) <- as.character(0:9)


training <- readRDS('data/training-arc-behavioral-eye-tracking-202311081400.rds') |>
    filter(
      phase=='Train' | item==1
    ) |>
    mutate(phase = fct_relabel(phase, \(x) case_match(x, 'Train'~'E', 'Test'~'Q')),
           io = fct_relabel(io, \(x) case_match(x, 'Input'~'In', 'Output'~'Out')))

path <- '/restricted/projectnb/cd-lab/Michael/human-arc/data/dataForQuan-202311071158'
files <- dir(path, full.names = TRUE, pattern='sub\\d+\\.csv$', recursive = TRUE)

etdata <- 
  set_names(files) |>
  map(read.csv) |>
  list_rbind(names_to='file') |>
  mutate(
    .before=1,
    dataset='pilot1',
    participant = interaction(dataset, as.integer(str_extract(basename(file), pattern='(?<=sub)\\d+')), sep='-'),
    problem = as.integer(str_extract(basename(file), pattern='(?<=prob)\\d+')),
    csperformance = factor(str_extract(file, '\\w+(?=Performance)'), c('low', 'high'))
  ) |>
  relocate(file, .after=last_col()) |>
  tibble()

path2 <- '/restricted/projectnb/cd-lab/Michael/human-arc/data/dataForQuan-202312061024/secondPilot'
files2 <- dir(path2, full.names = TRUE, pattern='prob\\d+\\.csv$', recursive = TRUE)
etdata2 <- 
  set_names(files2) |>
  map(read.csv) |>
  list_rbind(names_to='file') |>
  mutate(
    .before=1,
    dataset='pilot2',
    participant = interaction(dataset, sub, sep='-'),
    problem = as.integer(str_extract(basename(file), pattern='(?<=prob)\\d+')),
    csperformance = NA
  ) |>
  select(-sub) |>
  relocate(file, .after=last_col()) |>
  tibble()


etdata <- bind_rows(etdata, etdata2) |> mutate(across(problem, as.factor))

subject_id_map <- 
  rbind(
    mutate(read.csv(file.path(path, 'subIDs.csv')), dataset='pilot1-'),
    mutate(read.csv(file.path(path2, 'subIDs.csv')), dataset='pilot2-')
  )|>
  mutate(.keep='none', subject=json.ID, participant=as.factor(paste0(dataset, subject.number)))

etdata <- left_join(etdata, subject_id_map) |> relocate(subject, .after=participant)

ettheme <- 
  list(
      coord_fixed(),
      theme_linedraw(),
      theme(
        panel.background = element_rect(fill='transparent', color=NA),
        plot.background = element_rect(fill='transparent', color=NA),
        legend.background = element_rect(fill='transparent', color=NA),
        legend.key = element_rect(fill='transparent', color=NA),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.justification = c(0, 1)
      )
  )
```

# Eyetracking: Raw Fixation Data

## Raw Fixations - All Subjects

::: {layout-ncol="2" style="background-color: transparent;"}
```{r, eyetracking-all-subjects-screen, fig.cap='X-Y Screen Coordinates'}
ggplot(etdata) +
  geom_path(aes(x, y), color='grey80', alpha=.2) +
  geom_point(aes(x, y, color=scale(duration))) +
  scale_color_continuous('Duration (Z-Score)', type='viridis') +
  labs(
    x='X-Coordinate (Pixel)',
    y='Y-Coordinate (Pixel)'
  ) +
  ettheme
```

```{r, eyetracking-all-subjects-roi, fig.cap='By Region of Interest'}
etdata |>
  filter(!is.nan(tileX)) |>
  ggplot() +
  facet_wrap(vars(ROI), ncol=3, strip.position='bottom') +
  geom_path(aes(tileX, -tileY), color='grey80', alpha=.2) +
  geom_point(aes(tileX, -tileY, color=scale(duration))) +
  scale_color_continuous('Duration (Z-Score)', type='viridis') +
  labs(
    x='X-Coordinate (Tile)',
    y='Y-Coordinate (Tile)'
  ) +
  ettheme
```
:::

# Eyetracking: Subject-Level Plots

```{r, eyetracking-subject-plots, output='asis'}

plot_subject <- function (etdata_problem, training_problem) {
    
  if (nrow(etdata_problem) > 0)
    ggplot(training_problem) +
    geom_raster(aes(y, -x, fill=val)) +

    geom_path(data=etdata_problem,
              aes(tileX, -tileY), color='grey80', alpha=.2) +
    geom_point(data=etdata_problem,
               aes(tileX, -tileY, color=scale(duration)),
               shape='+') +
    
    scale_color_continuous('Duration (Z-Score)', type='viridis', guide='none') +
    
    facet_grid(interaction(phase, item, sep=' ', lex.order=TRUE) ~ io, switch='y') +
    
    # colors from common.css
    scale_fill_manual(values=arcpal, guide='none') +
    labs(x = NULL, y = NULL) +
    ettheme +
    theme(
      axis.title = element_blank(),
      plot.margin = unit(rep(0, 4), "null"),
      panel.spacing = unit(0, "null")
    )
  else
    ggplot() +
    annotate("text", x = 0.5, y = 0.5, label = "No data.", size = 5) +
    theme_void()
}

for (i in sort(unique(etdata$problem))) {

  cat('## Item ', i, ' - Fixations, By Subject\n\n')
  
  # Subset eyetracking data...
  etdata_problem <-
    etdata |>
    drop_na(tileX, tileY) |>
    filter(
      problem == i,
      between(ROI, 1, 8)
    ) |>
    mutate(
      # Are we looking at an example or test grid?
      phase = 
        case_when(between(ROI, 1, 6) ~ 0, .default=1) |>
        factor(0:1, c('E', 'Q')),
      
      # Are we looking at an input grid or an output grid?
      io = 
        case_when(ROI %in% c(1,3,5,7) ~ 0, .default=1) |>
        factor(0:1, c('In', 'Out')),
      
      # Are we looking at example or test one, two, three, ...? 
      item =
        case_when(
          ROI %in% 1:2 ~ 1,
          ROI %in% 3:4 ~ 2,
          ROI %in% 5:6 ~ 3,
          ROI %in% 7:8 ~ 1  # It's assumed that we have only the first test
        ) |>
        factor(1:6)
    )
  
  
  plot <-
    plot_grid(
      plotlist=lapply(
        split(etdata_problem, etdata_problem$participant),
        plot_subject,
        filter(training, task == i)
      ),
      labels=levels(etdata_problem$participant),
      scale=0.9, label_size = 10
    )
  

  print(plot)
  cat('\n\n')
}
```

# Task Items

```{r, output='asis'}
for (i in sort(unique(training$task))) {

  cat('## H-ARC Item ', i, '\n\n')
  
  plot <- {
    ggplot(filter(training, task == i)) +
    geom_raster(aes(y, -x, fill=val)) +
    
    facet_grid(interaction(phase, item, sep=' ', lex.order=TRUE) ~ io, switch='y') +
    
    scale_fill_manual(values=arcpal, guide='none') +
    labs(x = NULL, y = NULL) +
    ettheme +
    theme(
      axis.title = element_blank(),
      plot.margin = unit(rep(0, 4), "null"),
      panel.spacing = unit(0, "null")
    )
  }
  
  print(plot)
  cat('\n\n')
}
```
